name: "Search and Replace"
description: "Search and replace strings in files"
author: "Jason Finch"
inputs:
  include:
    description: "Files to include (supports glob patterns)"
    default: '**/*'
    required: false
  search:
    description: "String to search (or regex match)"
    required: true
  replace:
    description: "Replacement string"
    required: true
outputs:
  modifiedFiles:
    description: "The list of files modified"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: 'blue'
  icon: 'search'